import { build, context } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const watch = process.argv.includes('--watch');
const dev = watch || process.argv.includes('--dev');
const p = (...s) => resolve(root, ...s);

await mkdir(p('dist'), { recursive: true });
await mkdir(p('src/generated'), { recursive: true });

/**
 * Bake every sprite, icon and sound into the bundle as a data URI.
 *
 * The manifest declares no network access, so there is nowhere to fetch assets
 * from at runtime — and a plugin that reached out for its own sprites would be a
 * worse plugin anyway. Everything is small (~670kb raw), so inlining is simply
 * cheaper than the alternative.
 *
 * Only the UI imports this. The main thread never sees a data URI: it has no
 * base64 decoder and no canvas, so the UI decodes and slices, then posts raw PNG
 * bytes across. See tsconfig.main.json for why that split is enforced.
 */
async function generateAssets() {
  // Keyed by extension, and stated rather than guessed: a data URI carries no
  // filename, so the type in it is all the browser gets. Mislabel an Ogg stream and
  // it is left sniffing past a container that does not match.
  const MIME = {
    '.png': 'image/png',
    '.ogg': 'audio/ogg',
  };

  const groups = [
    { name: 'ICONS', dir: 'assets/icons', exts: ['.png'] },
    // The windows93 rip, one subdirectory per weapon. Keys keep the directory —
    // `0-hammer/hit-3` — because every weapon has its own hit-1, and a flat
    // namespace would have them overwrite each other silently.
    //
    // Images and audio are separate maps because the extension is stripped from the
    // key and upstream names a mark and its sound identically: 0-hammer/hit-1.png is
    // a crack, 0-hammer/hit-1.ogg is the thud it makes.
    { name: 'W93', dir: 'ref/w93', exts: ['.png'], nested: true },
    { name: 'W93_SOUNDS', dir: 'ref/w93', exts: ['.ogg'], nested: true },
  ];

  let out =
    '// GENERATED by scripts/build.mjs — do not edit, do not commit.\n' +
    '/* eslint-disable */\n\n';
  const report = [];

  /** Relative paths of every matching file, one level of nesting at most. */
  async function collect(dir, exts, nested) {
    const found = [];
    for (const entry of await readdir(p(dir), { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!nested) continue;
        for (const child of await readdir(p(dir, entry.name))) {
          if (exts.includes(extname(child).toLowerCase())) {
            found.push(`${entry.name}/${child}`);
          }
        }
      } else if (exts.includes(extname(entry.name).toLowerCase())) {
        found.push(entry.name);
      }
    }
    return found.sort();
  }

  for (const group of groups) {
    const files = await collect(group.dir, group.exts, group.nested ?? false);

    const entries = [];
    const seen = new Map();
    let bytes = 0;
    for (const file of files) {
      const ext = extname(file).toLowerCase();
      const mime = MIME[ext];
      if (!mime) throw new Error(`no mime mapped for ${ext} (${group.dir}/${file})`);
      // Strip only the extension, keep any directory: "0-hammer/hit-1".
      const key = file.slice(0, -ext.length);
      // Two files collapsing to one key would emit a duplicate object property —
      // invalid TypeScript, and whichever won would be arbitrary. Fail instead.
      if (seen.has(key)) {
        throw new Error(
          `${group.name}: "${key}" comes from both ${seen.get(key)} and ${file}. ` +
            `Split the group by extension or rename one.`,
        );
      }
      seen.set(key, file);
      const buf = await readFile(p(group.dir, file));
      bytes += buf.length;
      entries.push(`  ${JSON.stringify(key)}: "data:${mime};base64,${buf.toString('base64')}",`);
    }

    out += `export const ${group.name}: Record<string, string> = {\n${entries.join('\n')}\n};\n\n`;
    report.push(`${group.name} ${files.length} files ${(bytes / 1024).toFixed(0)}kb`);
  }

  await writeFile(p('src/generated/assets.ts'), out);
  console.log(`  assets: ${report.join(', ')}`);
}

await generateAssets();

/** Main thread: one IIFE, no imports, no exports — the sandbox has no module loader. */
const mainConfig = {
  entryPoints: [p('src/main/index.ts')],
  outfile: p('dist/main.js'),
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  minify: !dev,
  sourcemap: dev ? 'inline' : false,
  logLevel: 'info',
};

/**
 * UI: the manifest's `ui` must be a single self-contained HTML file (Figma inlines
 * it as the `__html__` global), so we build to memory and splice JS + CSS into the
 * template rather than emitting linked assets.
 */
const uiConfig = {
  entryPoints: [p('src/ui/main.ts')],
  bundle: true,
  format: 'iife',
  target: 'es2020',
  platform: 'browser',
  minify: !dev,
  sourcemap: false,
  write: false,
  logLevel: 'silent',
  loader: { '.css': 'css' },
  outdir: p('dist'),
  plugins: [
    {
      name: 'inline-html',
      setup(b) {
        b.onEnd(async (result) => {
          if (result.errors.length) {
            for (const e of result.errors) console.error('  ui error:', e.text);
            return;
          }
          const tpl = await readFile(p('src/ui/index.html'), 'utf8');
          const grab = (ext) => result.outputFiles.find((f) => f.path.endsWith(ext))?.text ?? '';
          // Function replacers, not strings: `$&` and `$1` sequences occur inside
          // base64 payloads and a minified bundle, and would otherwise be
          // interpreted as backreferences.
          const html = tpl
            .replace('/*__CSS__*/', () => grab('.css'))
            .replace('/*__JS__*/', () => grab('.js'));
          await writeFile(p('dist/ui.html'), html);
          console.log(`  dist/ui.html  ${(html.length / 1024).toFixed(0)}kb`);
        });
      },
    },
  ],
};

if (watch) {
  const ctxs = await Promise.all([context(mainConfig), context(uiConfig)]);
  await Promise.all(ctxs.map((c) => c.watch()));
  console.log('watching…');
} else {
  await Promise.all([build(mainConfig), build(uiConfig)]);
}
